### ISSUE TITLE
Be aware about the BehaviorObservable.toPromise() not work as expected.

### ISSUE THREAD

**Issue by zixia** [Chatie/db#6]
We will expect it resolve immediately but it doesn't.

See: https://github.com/Reactive-Extensions/RxJS/issues/1088 - BehaviourSubject toPromise isn't working

UPDATE:

* [Observable.toPromise and Observable.last().subscribe are identical](https://stackoverflow.com/questions/45375853/is-observable-topromise-and-observable-last-subscribe-are-identical)

```ts
return new Promise((resolve, reject) => {
    let value;
    this.subscribe((x) => value = x, (err) => reject(err), () => resolve(value));
});
```

**Comment by zixia** [comment]
SOLUTION:

```ts
await behaviorSubject.asObservable.first().toPromise()
```

The magic resides in the above `first()` which will make it work as expected.

**Comment by ErraticFox** [comment]
UPDATE: for anyone else viewing this later the solution would be:

```ts 
await behaviorSubject.pipe(take(1)).toPromise()
```

**Comment by huan** [comment]
@ErraticFox Thanks! We are in the stage of RxJS 6 now! 🎉

**Comment by PabloPerezAguilo** [comment]
> UPDATE: for anyone else viewing this later the solution would be:
> 
> ```ts
> await behaviorSubject.pipe(take(1)).toPromise()
> ```
Works! Thx! Not all hero wear capes.

**Comment by ErraticFox** [comment]
@PabloPerezAguilo just make sure to pay the good deed forward. :)
